import {StyleSheet} from 'react-native';
import {windowHeight, windowWidth} from '../../../components/WindowDimensions';

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#FFFFFF'},
  head: {
    height: windowHeight / 17,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: windowWidth / 16.92,
  },
  bottomWrap: {
    height: 70,
  },
  wrap: {
    flex: 1,
  },
  headerContainer: {
    backgroundColor: '#FFFFFF',
    width: windowWidth,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerWrap: {
    backgroundColor: '#EBEFF5',
    width: '95%',
    height: '70%',
    borderRadius: 30,
    flexDirection: 'row',
  },
  headerContainer2: {
    width: '100%',
    height: 80,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerWrapDetail: {
    backgroundColor: '#EBEFF5',
    width: '95%',
    height: '70%',
    borderRadius: 30,
    flexDirection: 'row',
  },
  tabBarActive: {
    flex: 1,
    marginHorizontal: 2,
    marginVertical: 5,
    backgroundColor: '#085D7A',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textActive: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
    textAlign: 'center',
  },
  textNonActive: {
    color: '#085D7A',
    fontWeight: 'bold',
    fontSize: 13,
    textAlign: 'center',
  },
  tabBar: {
    flex: 1,
    marginVertical: 5,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EBEFF5',
  },
  imageAdmin: {
    width: 40,
    height: 40,
    alignSelf: 'center',
  },
  contentContainer: {
    flex: 1,
    marginHorizontal: 5,
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
  },
  contentProfile: {
    margin: 10,
    backgroundColor: '#FFFFFF',
    height: 100,
    borderRadius: 10,
  },
  iconContainer: {
    flexDirection: 'row',
  },
  icon: {
    width: 30,
    height: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    marginLeft: 10,
    marginBottom: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  content: {
    flex: 1,
    margin: 10,
    padding: 5,
    backgroundColor: '#EBEFF5',
    borderRadius: 10,
  },
  titleContent: {
    flexDirection: 'row',
  },
  title: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  email: {
    flex: 1,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContent: {
    height: 100,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },

  // Modal
  modalContainer: {
    height: '100%',
    backgroundColor: '#FFFFFF',
    marginTop: 350,
    marginBottom: 30,
  },
  modalContent: {
    height: 50,
    backgroundColor: '#EBEBEB',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  totalComment: {color: '#085D7A', fontSize: 18, fontWeight: '700'},
  contentModal: {paddingHorizontal: 20},
  boxInput: {
    height: 150,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#085D7A',
    marginVertical: 10,
  },
  textInput: {color: 'black'},
  cardComment: {
    height: 1,
    width: '100%',
    backgroundColor: '#EBEBEB',
    marginVertical: 10,
  },
  // Modal View style
  centeredcontainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
  },
  centeredView: {
    flex: 1,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#EBEFF5',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  inputContainer: {
    paddingHorizontal: 20,
    paddingVertical: 5,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    width: '35%',
    height: 35,
    borderRadius: 10,
    backgroundColor: '#085D7A',
    alignSelf: 'flex-end',
  },
  buttondelete: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    width: '35%',
    height: 35,
    borderRadius: 10,
    backgroundColor: '#DE1B1B',
    alignSelf: 'flex-end',
  },
  buttoncancel: {
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#085D7A',
    margin: 10,
    width: '35%',
    height: 35,
    borderRadius: 10,
    backgroundColor: '#085D7A',
    alignSelf: 'flex-end',
  },
  save: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderColor: '#085D7A',
    marginBottom: 10,
    color: 'black',
    height: 35,
    fontSize: 12,
  },
  h2: {
    fontSize: 14,
    fontWeight: '200',
    fontFamily: 'Roboto',
  },
  textEdit: {
    fontSize: 20,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    color: '#085D7A',
  },
  rowDelete: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
  },
  backRightBtn: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 75,
  },
  backRightBtn2: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 150,
    flexDirection: 'row',
  },
  backRightBtnRight: {
    backgroundColor: 'red',
    borderTopRightRadius: 5,
    borderBottomEndRadius: 5,
    right: 0,
  },
  backRightBtnRight2: {
    backgroundColor: '#4AC994',
    right: 75,
  },
  backRightBtnRight3: {
    backgroundColor: '#34A68A',
    right: 150,
  },
  rowBack: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 15,
    marginHorizontal: 8,
    margin: 5,
    borderRadius: 5,
  },
});

export default styles;
