import {StyleSheet} from 'react-native';
import {windowHeight, windowWidth} from '../../../components/WindowDimensions';
const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#FFFFFF'},
  head: {
    height: windowHeight / 17,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: windowWidth / 16.92,
  },
  bottomWrap: {
    height: windowHeight / 13,
  },
  wrap: {
    flex: 1,
  },
  headerContainer2: {
    width: '100%',
    height: 80,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerWrapDetail: {
    backgroundColor: '#EBEFF5',
    width: '95%',
    height: '70%',
    borderRadius: 30,
    flexDirection: 'row',
  },
  tabBarActive: {
    flex: 1,
    marginHorizontal: 2,
    marginVertical: 5,
    backgroundColor: '#085D7A',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textActive: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 13,
    textAlign: 'center',
  },
  textNonActive: {
    color: '#085D7A',
    fontWeight: 'bold',
    fontSize: 13,
    textAlign: 'center',
  },
  tabBar: {
    flex: 1,
    marginVertical: 5,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EBEFF5',
  },
  imageAdmin: {
    width: 40,
    height: 40,
    alignSelf: 'center',
  },
  contentContainer: {
    flex: 1,
    marginHorizontal: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginBottom: windowHeight / 12.34,
  },
  contentProfile: {
    margin: 10,
    backgroundColor: '#FFFFFF',
    height: 100,
    borderRadius: 10,
  },
  iconContainer: {
    flexDirection: 'row',
  },
  icon: {
    width: 30,
    height: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    margin: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  content: {
    flex: 1,
    margin: 10,
    padding: 5,
    backgroundColor: '#EBEFF5',
    borderRadius: 10,
    marginBottom: 20,
  },
  titleContent: {
    flexDirection: 'row',
  },
  title: {
    flex: 2,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  email: {
    flex: 1,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContent: {
    height: 100,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 10,
  },

  // Modal
  modalContainer: {
    height: '60%',
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  modalPromoteContainer: {
    width: '100%',
    padding: 15,
    backgroundColor: '#FFFFFF',
    marginTop: 650,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: '#EBEBEB',
  },
  modalContent: {
    height: 50,
    backgroundColor: '#EBEBEB',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  totalComment: {color: '#085D7A', fontSize: 18, fontWeight: '700'},
  contentModal: {padding: 15},
  boxInput: {
    height: 150,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#085D7A',
    marginTop: 15,
    maxWidth: '100%',
  },
  textInput: {color: 'black'},
  cardComment: {
    height: 1,
    width: '100%',
    backgroundColor: '#B5B5B5',
    marginVertical: 15,
  },
  // Modal View style
  centeredcontainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
  },
  centeredView: {
    flex: 1,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#EBEFF5',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  inputContainer: {
    paddingHorizontal: 20,
    paddingVertical: 5,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    width: '100%',
    height: 35,
    borderRadius: 10,
    backgroundColor: '#34A68A',
    alignSelf: 'center',
  },
  buttondelete: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    width: '30%',
    height: 35,
    borderRadius: 10,
    backgroundColor: '#085D7A',
    alignSelf: 'center',
  },
  buttoncancel: {
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#DE1B1B',
    borderWidth: 1,
    margin: 10,
    width: '30%',
    height: 35,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
  },
  save: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  batal: {
    color: '#DE1B1B',
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderColor: '#085D7A',
    marginBottom: 10,
    color: 'black',
    height: 35,
    fontSize: 12,
  },
  inputAbout: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderColor: '#085D7A',
    marginBottom: 10,
    color: 'black',
    height: 85,
    fontSize: 12,
    width: '100%',
  },
  h1: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Roboto',
    marginBottom: 10,
    textAlign: 'justify',
  },
  h2: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Roboto',
    marginBottom: 10,
    textAlign: 'justify',
  },
  textEdit: {
    fontSize: 20,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    color: '#085D7A',
  },
  rowDelete: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
  },
  topLine: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowPromote: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 60,
  },
  wrapPromote: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  textPromote: {
    marginTop: 20,
    fontSize: 14,
    fontWeight: '700',
    color: '#085D7A',
  },
  textTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#085D7A',
  },
  titleWrap: {
    borderBottomWidth: 1,
    marginBottom: 10,
    borderBottomColor: '#085D7A',
  },
  buttonYakin: {
    flex: 1,
    backgroundColor: '#085D7A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textYakin: {color: '#FFFFFF', fontWeight: '700', fontSize: 16},
  buttonBatal: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DE1B1B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBatal: {color: '#DE1B1B', fontWeight: '700', fontSize: 16},
  gesture: {flex: 1},
  buttonWrap: {flexDirection: 'row', height: 50},
  lineSpace: {height: 3},
  textInputContainer: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#FFFFFF',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,

    elevation: 15,
  },
  textInputWrap: {width: '100%', padding: 10},
  textInputRow: {
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#085D7A',
    borderRadius: 5,
  },
  buttonSend: {
    flex: 1,
    position: 'absolute',
    bottom: 15,
    right: 10,
  },
  textSend: {fontWeight: 'bold', color: '#085D7A'},
});

export default styles;
